services:
#    farola_user.example:
#        class: Farola\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    farola_user.user_provider.email_only:
        class: Farola\UserBundle\Security\EmailOnlyUserProvider
        public: false
        arguments: [@fos_user.user_manager]

    farola_user.admin.user:
        class: Farola\UserBundle\Admin\UserAdmin
        arguments: [~, Farola\UserBundle\Entity\User, FarolaUserBundle:UserAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: User}

    # farola_user.security.authentication_event_subscriber:
    #     class: Farola\UserBundle\Subscriber\AuthenticationSubscriber
    #     calls:
    #     - [ setProfileHelper, [@farola_profile.helper] ]
    #     tags:
    #         - { name: kernel.event_subscriber }

    farola_user.profile.form.type:
        class: Farola\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: farola_user_profile }
