imports:
    - { resource: parameters.yml }
    - { resource: '../../../parameters_prod.yml', ignore_errors: true }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: v0.3.1
        #assets-base-url: /Farola/web
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        ph: @farola_profile.helper
        nh: @farola_notice.helper
        mh: @farola_message.helper
        rdh: @farola.ref_data.helper
    form:
        resources:
            - 'FarolaMainBundle:Common:farola_collection_block.html.twig'
            - 'FarolaMainBundle:Common:farola_location_block.html.twig'
            - 'FarolaMainBundle:Common:farola_tag_block.html.twig'
            - 'FarolaMainBundle:Common:farola_filterable_select_block.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
    workers:
        cache_busting: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#fos user bundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Farola\UserBundle\Entity\User
    registration:
        confirmation:
            from_email:
                address:        noreply@farolang.com
                sender_name:    Farolang
            enabled:    true # change to true for required email confirmation
            template:   FarolaUserBundle:Registration:email.txt.twig
    resetting:
        email:
            from_email:
                address:        noreply@farolang.com
                sender_name:    Farolang
    profile:
        form:
            type: farola_user_profile
    service:
        mailer: fos_user.mailer.twig_swift

#fos message bundle
#fos_message:
#    db_driver: orm
#    thread_class: Farola\MessageBundle\Entity\Thread
#    message_class: Farola\MessageBundle\Entity\Message

#jms i18n bundle
#jms routing bundle
#jms_i18n_routing:
#    default_locale: en
#    locales: [en, fr]
#    strategy: prefix

#Sonata admin bundle (block)
sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks

#stof doctrine extensions
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            softdeleteable: true

#lexic currency bundle
lexik_currency:
    currencies:
        default: EUR              # [required] the default currency
        managed:   # overrided by FarolaCurrencyBundle
    oer_app_id: ed6d489d7032480a9d018bb8e74a95b2

#add twig extension
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
