# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        ##Symfony\Component\Security\Core\User\User: plaintext
        #FOS user bundle
        FOS\UserBundle\Model\UserInterface: sha512

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_PREMIUM_USER:       ROLE_USER
        ROLE_VIP_USER:       ROLE_PREMIUM_USER
        ROLE_ADMIN:       ROLE_VIP_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        ##in_memory:
            ##memory:
                ##users:
                    ##user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    ##admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        #FOS user bundle
        fos_userbundle:
            id: fos_user.user_provider.username_email
            #id: farola_user.user_provider.email_only

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #FOS user bundle
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path:  /connection/security/login
                check_path:  /connection/security/login_check
            logout:
                target: farola_home
                path:   /connection/security/logout
            anonymous:    true
            switch_user: true

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #fos user bundle
        - { path: ^/connection, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/notice/board, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/notice/show/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/board, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: ROLE_USER }
        - { path: ^/notice, role: ROLE_USER }
        - { path: ^/message, role: ROLE_USER }
        - { path: ^/user, role: ROLE_USER }
